### ISSUE TITLE
Feature Request:  Integrate the .tlt file into .aux?

### ISSUE THREAD

**Issue by billdenney** [paolobrasolin/topiclongtable#11]
When compiling a .tex file with topiclongtable, a .tlt file is created.  Is it feasible to move the contents of the .tlt file into the .aux file?  That will help with standard LaTeX clean-up routines which remove extra files after compilation.

These instructions seem relevant: https://tex.stackexchange.com/questions/115932/on-the-basics-of-writing-to-reading-from-auxiliary-files-aux-toc-etc

**Comment by paolobrasolin** [comment]
Generally speaking, even pretty common packages (`synctex`, `beamer`, `biblatex`) generate files with extensions (`.synctex.gz`,  `.nav`, `.vrb`,  `.snm`, `.blg`, `-blx.bib`,  `.bbl`, `.run.xml`) that are not caught by common cleanup tools.

Furthermore, switching to using `.aux` instead of a separate file `.tlt` is possible but *not trivial*.

If you're using `latexmk` (which is what's typically used to handle multiple compliation passes, especially necessary with `topiclongtable`) you can configure the extensions the cleanup command `latex -c` by using a dotfile `.latexmkrc` containing any extension you want to delete:
```perl
@generated_exts = qw(aux idx ind lof lot out toc acn acr alg glg glo gls ist tls);
```

Another way would be to compile with an output dir flag:
```
latexmk -output-directory=tmp main.tex
```
That way all auxiliary files are contained in a single isolated folder, easy to delete. (The flag is accepted by engines like `pdflatex` too.)

What do you think @billdenney ?

**Comment by billdenney** [comment]
I had thought that the switch to .aux may be trivial.  If it's not, then no worries, and let's keep the `.tlt` file.
