### ISSUE TITLE
Error When Two Tables Have the Same Topic

### ISSUE THREAD

**Issue by billdenney** [paolobrasolin/topiclongtable#13]
Hi @paolobrasolin,

I was generating a long set of tables for a report today, and I encountered an error:

```
! Undefined control sequence.
<argument> \ERROR 
                  
l.250 \TopicLine \Topic[1]
                           & \Topic[  1] &   1 \\ 
```

The error appears to occur when two tables in sequence have the same `\Topic`.  It is possibly specific to the first column.  I've attached an example (just rename them both to .tex).

[fancytitle.txt](https://github.com/paolobrasolin/topiclongtable/files/3366366/fancytitle.txt)
[Untitled.txt](https://github.com/paolobrasolin/topiclongtable/files/3366367/Untitled.txt)

**Comment by paolobrasolin** [comment]
Hi @billdenney.

The `\ERROR` is a macro I planted myself to catch a subtle bug which I wasn't sure that would happen. So we're actually in luck you caught this.

Here's a MWE to reproduce the error:

```
\documentclass{article}
\usepackage{topiclongtable}
\begin{document}
  \begin{topiclongtable}{Fr}
    \Topic[1] \\
  \end{topiclongtable}
  \begin{topiclongtable}{Fr}
    \Topic[1] \\
  \end{topiclongtable}
\end{document}
```

The bug happens when the first root topic of a table is equal to the last root topic of the previous table.

**Comment by billdenney** [comment]
That is great defensive programming!
